#report
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
def generate_ecg_report(patient_name, age, date_of_test, time_of_test, location, result, features, filename="ECG_Report.pdf"):
    c = canvas.Canvas(filename, pagesize=A4)

    c.setFont("Helvetica-Bold", 18)
    c.drawString(100, 800, "AI-Based Heart Attack Detection Report")
    c.setFont("Helvetica", 12)
    c.drawString(180, 780, "(Using ECG Signal Analysis)")
    c.line(50, 770, 550, 770)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 750, "Patient Information:")
    c.setFont("Helvetica", 12)
    c.drawString(70, 730, f"Patient Name: {patient_name}")
    c.drawString(70, 710, f"Age: {age} years")
    c.drawString(70, 690, f"Date of Test: {date_of_test}")
    c.drawString(70, 670, f"Time of Test: {time_of_test}")
    c.drawString(70, 650, f"Test Location: {location}")

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, 620, "Extracted ECG Features:")
    y = 600
    c.setFont("Helvetica", 12)
    for key, value in features.items():
        c.drawString(70, y, f"{key}: {value}")
        y -= 20

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y - 10, "ML Model Prediction:")
    c.setFont("Helvetica", 12)
    c.drawString(70, y - 30, f"Prediction Result: {result}")

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y - 70, "Conclusion:")
    c.setFont("Helvetica", 12)
    if result.lower() == "normal":
        c.drawString(70, y - 90, "✅ ECG signal appears normal. No signs of heart attack detected.")
    else:
        c.drawString(70, y - 90, "⚠ Possible heart attack detected. Immediate medical consultation advised.")

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 80, "Generated by: AI-Based ECG Heart Guardian System")
    c.drawString(50, 65, f"Report Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}")
    c.drawString(50, 50, "This is a computer-generated report and does not require a physical signature.")
    c.save()
    print(f"✅ Report saved as {filename}")
features = {
    "Mean": 0.023,
    "Standard Deviation": 0.0041,
    "RMS": 0.011,
    "Skewness": 0.43,
    "Kurtosis": 2.19,
    "Heart Rate": "78 BPM"
}
generate_ecg_report(
    patient_name="Shagun Pal",
    age=19,
    date_of_test="8th November 2025",
    time_of_test="11:45 AM",
    location="Heart Guardian Prototype",
    result="Normal",
    features=features
)